module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]

// 15 photos for now
module.exports.imageFileNames = [
    'YelpCamp/zirydfeyo1bbcp4ukwtb',
    'YelpCamp/fhjnmpidd6mglrifvenr',
    'YelpCamp/grkif8bb3yl5glhvziiy',
    'YelpCamp/mrikv6whjabcorttycli',
    'YelpCamp/zhelhmxs2uqf0pomztkm',
    'YelpCamp/ys0iym2gbp8rvcpucxua',
    'YelpCamp/thbprwz419qjearpkrvl',
    'YelpCamp/vapdmtljyu1bpbehkdjm',
    'YelpCamp/l8pbzxdnhaawi0buzpjd',
    'YelpCamp/uzufvourozfrerxzunab',
    'YelpCamp/u6tkyspghrwqi6vkva9z',
    'YelpCamp/ytohac44ehh2k7ornrkd',
    'YelpCamp/u9z5a6ooyjqnrcef3cca',
    'YelpCamp/lqiwbdftt6bor8opmrpx',
    'YelpCamp/nkkrekd2v0k25uekhrqe'
];
module.exports.imageURLs = [
    'https://res.cloudinary.com/dmwriqbhu/image/upload/v1615489207/YelpCamp/zirydfeyo1bbcp4ukwtb.jpg',
    'https://res.cloudinary.com/dmwriqbhu/image/upload/v1615489207/YelpCamp/fhjnmpidd6mglrifvenr.jpg',
    'https://res.cloudinary.com/dmwriqbhu/image/upload/v1615489207/YelpCamp/grkif8bb3yl5glhvziiy.jpg',
    'https://res.cloudinary.com/dmwriqbhu/image/upload/v1615489207/YelpCamp/mrikv6whjabcorttycli.jpg',
    'https://res.cloudinary.com/dmwriqbhu/image/upload/v1615489207/YelpCamp/zhelhmxs2uqf0pomztkm.jpg',
    'https://res.cloudinary.com/dmwriqbhu/image/upload/v1615489207/YelpCamp/ys0iym2gbp8rvcpucxua.jpg',
    'https://res.cloudinary.com/dmwriqbhu/image/upload/v1615489207/YelpCamp/thbprwz419qjearpkrvl.jpg',
    'https://res.cloudinary.com/dmwriqbhu/image/upload/v1615489207/YelpCamp/vapdmtljyu1bpbehkdjm.jpg',
    'https://res.cloudinary.com/dmwriqbhu/image/upload/v1615489207/YelpCamp/l8pbzxdnhaawi0buzpjd.jpg',
    'https://res.cloudinary.com/dmwriqbhu/image/upload/v1615489207/YelpCamp/uzufvourozfrerxzunab.jpg',
    'https://res.cloudinary.com/dmwriqbhu/image/upload/v1615489206/YelpCamp/u6tkyspghrwqi6vkva9z.jpg',
    'https://res.cloudinary.com/dmwriqbhu/image/upload/v1615489206/YelpCamp/ytohac44ehh2k7ornrkd.jpg',
    'https://res.cloudinary.com/dmwriqbhu/image/upload/v1615489206/YelpCamp/u9z5a6ooyjqnrcef3cca.jpg',
    'https://res.cloudinary.com/dmwriqbhu/image/upload/v1615489206/YelpCamp/lqiwbdftt6bor8opmrpx.jpg',
    'https://res.cloudinary.com/dmwriqbhu/image/upload/v1615489206/YelpCamp/nkkrekd2v0k25uekhrqe.jpg'
]